name: Build and Deploy ASP.NET Core 8.0 App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore PROYECTOPDFVFINAL

      - name: Build
        run: dotnet build --configuration Release --no-restore PROYECTOPDFVFINAL

      - name: Publish
        run: dotnet publish PROYECTOPDFVFINAL -c realease -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'proyectopdffinalversion' # Reemplaza con el nombre de tu Azure Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: PROYECTOPDFVFINAL