name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20.0.2'

    - name: Build with Ant
      run: ant -f ProyectoPDF/ProyectoPDF/ProyectoPDF/build.xml dist

    - name: Deploy to Tomcat
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: 'ProyectoPDF/ProyectoPDF/ProyectoPDF/dist/ProyectoPDF.war'
        target: '/path/to/your/tomcat/webapps/'